version: "3"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=spring-security-jwt
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"